### ISSUE TITLE
how to set up a consumer to consume avro record from kafka into mysql

### ISSUE THREAD

**Issue by wanghaisheng** [outbrain/Aletheia#16]
i am trying to use linkedin databus, it can parse mysql binlog into avro record and then pipe into  kafka,then i want to use your nice work to build a consumer to recreate mysql database from these data in kafka. 
could you show me some config or example

**Comment by staslev** [comment]
Hi,

I'm afraid I'll have to start with a disclaimer as I'm not familiar with the format and structure of the binlog messages databus sends to Kafka, but the chances of them being compatible with Aletheia out of the box are pretty slim.

Would you mind telling a bit more about what your end goal? 
Is your task a one off or a recurring job? 
Are you interested in fine grained monitoring of the database reconstruction process (e.g., monitor that every statement that was sent to Kafka has indeed been consumed [and executed] by the consumer on the other end)?

For instance, If it's a one off I could suggest building a Kafka consumer with a [custom message decoder](https://github.com/apache/kafka/blob/b62f8ea43b6d5307f7274fbe8b7984dd5ee22239/core/src/main/scala/kafka/serializer/Decoder.scala) such that can read databus messages (i.e., the deserialization side of things).

If it's more of a recurring procedure then it sounds like you may care about metrics and visibility, and this is where Aletheia might be able to provide value. For this to work you need to have databus send its messages using an Aletheia producer (you are welcome to take a look at the [architectural overview](https://github.com/outbrain/Aletheia/wiki/Architectural-Overview) wiki) so that you could use Aletheia consumer on the other end of the pipeline.

Let's us know if it's the latter, in which case we might be able to look deeper into it and provide some more insights.

-Stas

**Comment by wanghaisheng** [comment]
definitely   ecurring procedure one.
right now  we have online business using mysql as databases ,we want  a pipeline to chain the data into our local data center,one purpose is to share the pressure of disk space , one purpose is to run analylst in our data center to investigate value of these data,
then we came to a binlog replication solutions ,which databus act as a producer and consumer,we want to use kafka as the unique in message point ,then build one or more business modules to deal with all kinds of analyzing job or providing the mysql access to online  business .
for the latter one  then i want to consumer the messages stored in kafka  and rebuild the mysql database  ,the only left job to online business  is changing the ip address and port of  mysql connection without any changes to the original source codes.

**Comment by staslev** [comment]
Thanks for the info.

In order to be able to benefit from Aletheia you will need to have Aletheia on both sides of the pipeline. That is, you will need to change databus so that is uses an Aletheia producer to send data into Kafka, and then use an Aletheia consumer in your application to consume data on the other end of the pipeline.

I hope this clarifies things a bit.

-Stas

**Comment by staslev** [comment]
I'm going to close this issue for now, please feel free to re-open it or report a new one in case you decide to go forward with the databus integration and encounter any difficulties. Also, if that is indeed the case, we'd love to hear about your experience getting it done.

-Stas
